

version: '3.8'

services:
  app :
    build: .

    container_name: clon_spotify_backend

    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      - URL_DATABASE=${URL_DATABASE}
      - USERNAME_DATABASE=${USERNAME_DATABASE}
      - PASSWORD_DATABASE=${PASSWORD_DATABASE}
      - EMAIL_EMISOR=${EMAIL_EMISOR}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - JWT_VARIABLE=${JWT_VARIABLE}
      - JWT_EXPIRATION_ACCESS=${JWT_EXPIRATION_ACCESS}
      - JWT_EXPIRATION_REFRESH=${JWT_EXPIRATION_REFRESH}


