# src/main/resources/application.yml

spring:
  server:
    address : 0.0.0.0
    port : 8080

  datasource:
    url: ${URL_DATABASE}
    username: ${USERNAME_DATABASE}
    password: ${PASSWORD_DATABASE}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  mail :
    host : smtp.gmail.com
    port : 587
    username : ${EMAIL_EMISOR}
    password : ${EMAIL_PASSWORD}
    properties :
      mail :
        smtp :
          auth :
            true
          starttls :
            enable : true

api :
  gemini :
    key : ${GOOGLE_API_KEY}

jwt :
  variable : ${JWT_VARIABLE}
  expiration :
    access : ${JWT_EXPIRATION_ACCESS}
    refresh : ${JWT_EXPIRATION_REFRESH}
